#!/usr/bin/env node

const fs = require("fs");
const { PDFDocument } = require("pdf-lib");
const path = require("path");
const os = require("os");

const excludedFields = ["hidden"];

async function extractFields(pdfPath) {
  const pdfBytes = fs.readFileSync(pdfPath);
  const pdfDoc = await PDFDocument.load(pdfBytes, { ignoreEncryption: true });
  const form = pdfDoc.getForm();
  const fields = form.getFields();

  const otherFields = [];
  const numericFields = [];

  fields.map((field) => {
    const fieldName = field.getName();
    if (excludedFields.includes(fieldName)) {
      return;
    }

    if (fieldName.match(/^\d/)) {
      numericFields.push({
        name: fieldName,
        value: fieldName.match(/^\d+$/) ? fieldName : "",
      });
    } else {
      otherFields.push({ name: fieldName, value: "" });
    }
  });

  return [...numericFields, ...otherFields].map(({ name, value }) => {
    return `${name}": "${value}`;
  });
}

async function saveFormFieldsAsJson(pdfPath) {
  const fieldData = await extractFields(pdfPath);

  const outputDir = path.join(os.homedir(), "Downloads", "pdf-to-json");
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const outputFileName =
    path.basename(pdfPath, path.extname(pdfPath)) + ".json";
  const outputPath = path.join(outputDir, outputFileName);

  const json = JSON.stringify(fieldData, null, 2)
    .replaceAll('\\"', '"')
    .replace("[", "{");

  fs.writeFileSync(outputPath, `${json.slice(0, -1)}}`);
  console.log(`JSON generated at location: ${outputPath}`);
}

const pdfFilePath = process.argv[2];

if (!pdfFilePath) {
  console.error("Please provide the base PDF to work with.");
  process.exit(1);
}

saveFormFieldsAsJson(pdfFilePath).catch((err) =>
  console.error("An error encountered during PDF to JSON parsing:", err)
);
